[package]
name = "rocksdb"
description = "A Rust wrapper for Facebook's RocksDB embeddable database."
version = "0.3.0"
authors = ["Tyler Neely <t@jujit.su>", "David Greenberg <dsg123456789@gmail.com>"]
license = "Apache-2.0"
keywords = ["database", "embedded", "LSM-tree", "persistence"]
homepage = "https://github.com/spacejam/rust-rocksdb"
exclude = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "tests/**/*",
  "benches/**/*",
]

[features]
default = []
valgrind = []
portable = ["librocksdb_sys/portable"]
sse = ["librocksdb_sys/sse"]

[dependencies]
libc = "0.2.11"
crc = "1.2"

[dependencies.librocksdb_sys]
path = "librocksdb_sys"

[dev-dependencies]
byteorder = "1.0.0"
rand = "0.3"
tempdir = "0.3"
